### ISSUE TITLE
是否应该有个环境变量

### ISSUE THREAD

**Issue by qq157788394** [megalojs/megalo-cli#2]
环境变量，区分dev和prod模式，因为测试和正式的接口调用地址是不一样的。

**Comment by zwwill** [comment]
好提议！已录入需求池

**Comment by qq157788394** [comment]
亲，环境变量的需求，您是准备啥时候放进去啊？

**Comment by zwwill** [comment]
sorry，遗漏的这条issue，因为人手不足，环境变量的需求还没拍到，你是有强依赖吗？如果是，我下周提高一下优先级

**Comment by qq157788394** [comment]
> sorry，遗漏的这条issue，因为人手不足，环境变量的需求还没拍到，你是有强依赖吗？�如果是，我下周提高一下优先级

感谢！(づ￣3￣)づ╭❤～

**Comment by bigmeow** [comment]
@qq157788394  久等了，还没发包（内测），你可以clone这项目先试用下：https://github.com/bigmeow/megalo-demo
使用文档参照[vue-cli3](https://cli.vuejs.org/zh/guide/mode-and-env.html#%E6%A8%A1%E5%BC%8F)
有问题可提

**Comment by NextBoy** [comment]
这个直接配置在命令行里面不就行了？
```
    "dev:wechat": "NODE_ENV=development webpack --config ./build/webpack.config.wechat.js -w",
    "build:wechat": "NODE_ENV=production webpack --config ./build/webpack.config.wechat.js -w"
```

**Comment by bigmeow** [comment]
@NextBoy 如果有5，6个环境变量呢？ 这个主要应用场景是 ` 在不同的环境中 不改代码的情况下自动使用对应的API接口域名`
