### ISSUE TITLE
es6转es5勾选之后 报错

### ISSUE THREAD

**Issue by DestinyHunter** [megalojs/megalo-cli#27]
使用原生组件需要勾选es6转es5 ,勾选之后报错,,
![image](https://user-images.githubusercontent.com/20897838/55206301-f41ce700-5210-11e9-9549-4a15715cdce2.png)

**Comment by bigmeow** [comment]
https://github.com/bigmeow/megalo-cli/tree/master/packages/@megalo/cli-plugin-flx-es6-to-es5
