### ISSUE TITLE
[Bug] 初始化选择 sass 时少安装了 node-sass

### ISSUE THREAD

**Issue by auven** [megalojs/megalo-cli#30]
![image](https://user-images.githubusercontent.com/23731087/55463642-16a56a80-562c-11e9-8fe3-5b10666836dc.png)

![image](https://user-images.githubusercontent.com/23731087/55463683-2755e080-562c-11e9-9e17-8ef95963d958.png)

**Comment by bigmeow** [comment]
已修复。
```sao npm:@megalo/cli@latest your-project-name --update```
可忽略缓存拉取最新模版
