### ISSUE TITLE
对引入第三方插件很不友好啊，能优化吗

### ISSUE THREAD

**Issue by webtianjia** [megalojs/megalo-cli#35]
![image](https://user-images.githubusercontent.com/22638382/57756205-5a0ff000-7725-11e9-83e7-2d6db52791b0.png)
  重新运行编译， 就被clear 掉了，我得重新关掉微信开发者工作，然后重新copy第三方ui 。。。
 求大佬教一下解决办法！不胜感激

**Comment by bigmeow** [comment]
https://megalojs.org/#/cli/megalo-config-js?id=nativedir

**Comment by webtianjia** [comment]
@bigmeow  搞定了 非常感谢 来自菜鸡的摩拜
