### ISSUE TITLE
@megalo/vue-template-compiler 与@megalo/vue包不一致

### ISSUE THREAD

**Issue by hoelshen** [megalojs/megalo-cli#38]
using @megalo/template-compiler@0.10.1
using megalo@0.10.1
(node:25661) UnhandledPromiseRejectionWarning: Error: 

Vue packages version mismatch:

- vue@2.6.10
- vue-template-compiler@2.5.17

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by bigmeow** [comment]
- 项目的package.json 文件里不要同时引用 `vue` 包 和 `megalo` 包
- 如果是编译h5,2个包的版本写死：
```
"vue": "2.5.17",
"vue-template-compiler": "2.5.17"
```

你是要编译h5还是小程序

**Comment by hoelshen** [comment]
采用ts情况下 ，已解决。
